apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backendconfig
spec:
  cdn:
    enabled: false
  timeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
  customRequestHeaders:
    headers:
      - "X-Client-Region:{client_region}"
      - "X-Forwarded-For:{client_ip}"
