apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
        - name: user-frontend
          image: gcr.io/gen-lang-client-0149291660/user-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
