apiVersion: v1
kind: Service
metadata:
  name: user-frontend-service
spec:
  selector:
    app: user-frontend
  ports:
    - port: 80
      targetPort: 80
    # OPTIONAL: conversational websocket port (remove if not needed)
    - port: 3000
      targetPort: 3000
  type: ClusterIP
