apiVersion: v1
kind: Service
metadata:
  name: user-frontend-service
  annotations:
    cloud.google.com/backend-config: '{"default": "frontend-backendconfig"}'
spec:
  selector:
    app: user-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
